version: "3.2"

services:
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
    depends_on :
      - php

  php:
    build:
      context: docker/php-cli
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    depends_on:
      - postgres

  postgres:
    image: postgres:10
    environment:
      - POSTGRES_DB=weather_history
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - "25432:5432"
